#!/bin/sh

# Watches a directory for changes in files and runs go test with a clear cache 
# Requires watchexec program

BBLUE='\033[1;34m'        # Blue
watchexec "echo \"${BBLUE}[$(date -u +'%Y-%m-%dT%H:%M:%SZ')]    RUNNING CLI BUILD ${BBLUE}\" && make cli-dev"
