#!/bin/sh

# Watches a directory for changes in files and runs go test with a clear cache 
# Requires watchexec program

BBLUE='\033[1;34m'        # Blue
watchexec "echo \"${BBLUE}    RUNNING BUILD ${BLUE}\" && go build ."
