#!/bin/sh

# Description: Delete all helm things

helm ls --all --short | xargs -L1 helm delete
kubectl delete --all jobs
kubectl delete --all statefulsets
kubectl delete --all daemonsets
kubectl delete --all replicasets
kubectl delete --all deployments
kubectl delete --all services
kubectl delete --all pvc
kubectl delete --all secrets
kubectl delete ns ns1
kubectl delete ns ns2
kubectl delete ns vault
kubectl patch crd/servicedefaults.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/serviceintentions.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/ingressgateways.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/meshes.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/proxydefaults.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/serviceresolvers.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/servicerouters.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/servicesplitters.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/terminatinggateways.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/controlplanerequestlimits.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/exportedservices.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/gatewayclassconfigs.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/jwtproviders.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/meshservices.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/samenessgroups.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/apigateways.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/exportedservices.multicluster.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/gatewayclassconfigs.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/gatewayclasses.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/gatewaypolicies.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/grpcroutes.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/httproutes.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/meshconfigurations.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/meshgateways.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/proxyconfigurations.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/routeauthfilters.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/routeretryfilters.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/routetimeoutfilters.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/tcproutes.mesh.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/trafficpermissions.auth.consul.hashicorp.com -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete crd/servicedefaults.consul.hashicorp.com
kubectl delete crd/serviceintentions.consul.hashicorp.com
kubectl delete crd/ingressgateways.consul.hashicorp.com
kubectl delete crd/meshes.consul.hashicorp.com
kubectl delete crd/proxydefaults.consul.hashicorp.com
kubectl delete crd/serviceresolvers.consul.hashicorp.com
kubectl delete crd/servicerouters.consul.hashicorp.com
kubectl delete crd/servicesplitters.consul.hashicorp.com
kubectl delete crd/terminatinggateways.consul.hashicorp.com
kubectl delete crd/controlplanerequestlimits.consul.hashicorp.com
kubectl delete crd/exportedservices.consul.hashicorp.com
kubectl delete crd/gatewayclassconfigs.consul.hashicorp.com
kubectl delete crd/jwtproviders.consul.hashicorp.com
kubectl delete crd/meshservices.consul.hashicorp.com
kubectl delete crd/samenessgroups.consul.hashicorp.com
kubectl delete crd/apigateways.mesh.consul.hashicorp.com
kubectl delete crd/exportedservices.multicluster.consul.hashicorp.com
kubectl delete crd/gatewayclassconfigs.mesh.consul.hashicorp.com
kubectl delete crd/gatewayclasses.mesh.consul.hashicorp.com
kubectl delete crd/gatewaypolicies.consul.hashicorp.com
kubectl delete crd/grpcroutes.mesh.consul.hashicorp.com
kubectl delete crd/httproutes.mesh.consul.hashicorp.com
kubectl delete crd/meshconfigurations.mesh.consul.hashicorp.com
kubectl delete crd/meshgateways.mesh.consul.hashicorp.com
kubectl delete crd/proxyconfigurations.mesh.consul.hashicorp.com
kubectl delete crd/routeauthfilters.consul.hashicorp.com
kubectl delete crd/routeretryfilters.consul.hashicorp.com
kubectl delete crd/routetimeoutfilters.consul.hashicorp.com
kubectl delete crd/tcproutes.mesh.consul.hashicorp.com
kubectl delete crd/trafficpermissions.auth.consul.hashicorp.com
# Delete non-consul gateway CRDs
kubectl patch crd/gatewayclasses.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/gateways.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/grpcroutes.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/httproutes.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/referencegrants.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/tcproutes.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/tlsroutes.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch crd/udproutes.gateway.networking.k8s.io -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete crd/gatewayclasses.gateway.networking.k8s.io
kubectl delete crd/gateways.gateway.networking.k8s.io
kubectl delete crd/grpcroutes.gateway.networking.k8s.io
kubectl delete crd/httproutes.gateway.networking.k8s.io
kubectl delete crd/referencegrants.gateway.networking.k8s.io
kubectl delete crd/tcproutes.gateway.networking.k8s.io
kubectl delete crd/tlsroutes.gateway.networking.k8s.io
kubectl delete crd/udproutes.gateway.networking.k8s.io
